// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: base/eventid.proto

package com.beeswax.base;

public final class Eventid {
  private Eventid() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface EventIdOrBuilder extends
      // @@protoc_insertion_point(interface_extends:base.EventId)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 32 bits of md5 hash
     * </pre>
     *
     * <code>optional uint32 hostid = 1;</code>
     * @return Whether the hostid field is set.
     */
    boolean hasHostid();
    /**
     * <pre>
     * 32 bits of md5 hash
     * </pre>
     *
     * <code>optional uint32 hostid = 1;</code>
     * @return The hostid.
     */
    int getHostid();

    /**
     * <code>optional uint32 tid = 2;</code>
     * @return Whether the tid field is set.
     */
    boolean hasTid();
    /**
     * <code>optional uint32 tid = 2;</code>
     * @return The tid.
     */
    int getTid();

    /**
     * <code>optional uint64 timestamp = 3;</code>
     * @return Whether the timestamp field is set.
     */
    boolean hasTimestamp();
    /**
     * <code>optional uint64 timestamp = 3;</code>
     * @return The timestamp.
     */
    long getTimestamp();

    /**
     * <pre>
     * Impression index within the request
     * </pre>
     *
     * <code>optional uint32 imp_idx = 4;</code>
     * @return Whether the impIdx field is set.
     */
    boolean hasImpIdx();
    /**
     * <pre>
     * Impression index within the request
     * </pre>
     *
     * <code>optional uint32 imp_idx = 4;</code>
     * @return The impIdx.
     */
    int getImpIdx();
  }
  /**
   * Protobuf type {@code base.EventId}
   */
  public static final class EventId extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:base.EventId)
      EventIdOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use EventId.newBuilder() to construct.
    private EventId(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private EventId() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new EventId();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private EventId(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              hostid_ = input.readUInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              tid_ = input.readUInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              timestamp_ = input.readUInt64();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              impIdx_ = input.readUInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.beeswax.base.Eventid.internal_static_base_EventId_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.beeswax.base.Eventid.internal_static_base_EventId_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.beeswax.base.Eventid.EventId.class, com.beeswax.base.Eventid.EventId.Builder.class);
    }

    private int bitField0_;
    public static final int HOSTID_FIELD_NUMBER = 1;
    private int hostid_;
    /**
     * <pre>
     * 32 bits of md5 hash
     * </pre>
     *
     * <code>optional uint32 hostid = 1;</code>
     * @return Whether the hostid field is set.
     */
    @java.lang.Override
    public boolean hasHostid() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * 32 bits of md5 hash
     * </pre>
     *
     * <code>optional uint32 hostid = 1;</code>
     * @return The hostid.
     */
    @java.lang.Override
    public int getHostid() {
      return hostid_;
    }

    public static final int TID_FIELD_NUMBER = 2;
    private int tid_;
    /**
     * <code>optional uint32 tid = 2;</code>
     * @return Whether the tid field is set.
     */
    @java.lang.Override
    public boolean hasTid() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional uint32 tid = 2;</code>
     * @return The tid.
     */
    @java.lang.Override
    public int getTid() {
      return tid_;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 3;
    private long timestamp_;
    /**
     * <code>optional uint64 timestamp = 3;</code>
     * @return Whether the timestamp field is set.
     */
    @java.lang.Override
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional uint64 timestamp = 3;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int IMP_IDX_FIELD_NUMBER = 4;
    private int impIdx_;
    /**
     * <pre>
     * Impression index within the request
     * </pre>
     *
     * <code>optional uint32 imp_idx = 4;</code>
     * @return Whether the impIdx field is set.
     */
    @java.lang.Override
    public boolean hasImpIdx() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     * Impression index within the request
     * </pre>
     *
     * <code>optional uint32 imp_idx = 4;</code>
     * @return The impIdx.
     */
    @java.lang.Override
    public int getImpIdx() {
      return impIdx_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeUInt32(1, hostid_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeUInt32(2, tid_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeUInt64(3, timestamp_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeUInt32(4, impIdx_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, hostid_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, tid_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, timestamp_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, impIdx_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.beeswax.base.Eventid.EventId)) {
        return super.equals(obj);
      }
      com.beeswax.base.Eventid.EventId other = (com.beeswax.base.Eventid.EventId) obj;

      if (hasHostid() != other.hasHostid()) return false;
      if (hasHostid()) {
        if (getHostid()
            != other.getHostid()) return false;
      }
      if (hasTid() != other.hasTid()) return false;
      if (hasTid()) {
        if (getTid()
            != other.getTid()) return false;
      }
      if (hasTimestamp() != other.hasTimestamp()) return false;
      if (hasTimestamp()) {
        if (getTimestamp()
            != other.getTimestamp()) return false;
      }
      if (hasImpIdx() != other.hasImpIdx()) return false;
      if (hasImpIdx()) {
        if (getImpIdx()
            != other.getImpIdx()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasHostid()) {
        hash = (37 * hash) + HOSTID_FIELD_NUMBER;
        hash = (53 * hash) + getHostid();
      }
      if (hasTid()) {
        hash = (37 * hash) + TID_FIELD_NUMBER;
        hash = (53 * hash) + getTid();
      }
      if (hasTimestamp()) {
        hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getTimestamp());
      }
      if (hasImpIdx()) {
        hash = (37 * hash) + IMP_IDX_FIELD_NUMBER;
        hash = (53 * hash) + getImpIdx();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.beeswax.base.Eventid.EventId parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.beeswax.base.Eventid.EventId parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.beeswax.base.Eventid.EventId parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.beeswax.base.Eventid.EventId parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.beeswax.base.Eventid.EventId parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.beeswax.base.Eventid.EventId parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.beeswax.base.Eventid.EventId parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.beeswax.base.Eventid.EventId parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.beeswax.base.Eventid.EventId parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.beeswax.base.Eventid.EventId parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.beeswax.base.Eventid.EventId parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.beeswax.base.Eventid.EventId parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.beeswax.base.Eventid.EventId prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code base.EventId}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:base.EventId)
        com.beeswax.base.Eventid.EventIdOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.beeswax.base.Eventid.internal_static_base_EventId_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.beeswax.base.Eventid.internal_static_base_EventId_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.beeswax.base.Eventid.EventId.class, com.beeswax.base.Eventid.EventId.Builder.class);
      }

      // Construct using com.beeswax.base.Eventid.EventId.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        hostid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        tid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        timestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        impIdx_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.beeswax.base.Eventid.internal_static_base_EventId_descriptor;
      }

      @java.lang.Override
      public com.beeswax.base.Eventid.EventId getDefaultInstanceForType() {
        return com.beeswax.base.Eventid.EventId.getDefaultInstance();
      }

      @java.lang.Override
      public com.beeswax.base.Eventid.EventId build() {
        com.beeswax.base.Eventid.EventId result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.beeswax.base.Eventid.EventId buildPartial() {
        com.beeswax.base.Eventid.EventId result = new com.beeswax.base.Eventid.EventId(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.hostid_ = hostid_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.tid_ = tid_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.timestamp_ = timestamp_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.impIdx_ = impIdx_;
          to_bitField0_ |= 0x00000008;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.beeswax.base.Eventid.EventId) {
          return mergeFrom((com.beeswax.base.Eventid.EventId)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.beeswax.base.Eventid.EventId other) {
        if (other == com.beeswax.base.Eventid.EventId.getDefaultInstance()) return this;
        if (other.hasHostid()) {
          setHostid(other.getHostid());
        }
        if (other.hasTid()) {
          setTid(other.getTid());
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (other.hasImpIdx()) {
          setImpIdx(other.getImpIdx());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.beeswax.base.Eventid.EventId parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.beeswax.base.Eventid.EventId) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int hostid_ ;
      /**
       * <pre>
       * 32 bits of md5 hash
       * </pre>
       *
       * <code>optional uint32 hostid = 1;</code>
       * @return Whether the hostid field is set.
       */
      @java.lang.Override
      public boolean hasHostid() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       * 32 bits of md5 hash
       * </pre>
       *
       * <code>optional uint32 hostid = 1;</code>
       * @return The hostid.
       */
      @java.lang.Override
      public int getHostid() {
        return hostid_;
      }
      /**
       * <pre>
       * 32 bits of md5 hash
       * </pre>
       *
       * <code>optional uint32 hostid = 1;</code>
       * @param value The hostid to set.
       * @return This builder for chaining.
       */
      public Builder setHostid(int value) {
        bitField0_ |= 0x00000001;
        hostid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 32 bits of md5 hash
       * </pre>
       *
       * <code>optional uint32 hostid = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearHostid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        hostid_ = 0;
        onChanged();
        return this;
      }

      private int tid_ ;
      /**
       * <code>optional uint32 tid = 2;</code>
       * @return Whether the tid field is set.
       */
      @java.lang.Override
      public boolean hasTid() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional uint32 tid = 2;</code>
       * @return The tid.
       */
      @java.lang.Override
      public int getTid() {
        return tid_;
      }
      /**
       * <code>optional uint32 tid = 2;</code>
       * @param value The tid to set.
       * @return This builder for chaining.
       */
      public Builder setTid(int value) {
        bitField0_ |= 0x00000002;
        tid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 tid = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTid() {
        bitField0_ = (bitField0_ & ~0x00000002);
        tid_ = 0;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>optional uint64 timestamp = 3;</code>
       * @return Whether the timestamp field is set.
       */
      @java.lang.Override
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional uint64 timestamp = 3;</code>
       * @return The timestamp.
       */
      @java.lang.Override
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>optional uint64 timestamp = 3;</code>
       * @param value The timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestamp(long value) {
        bitField0_ |= 0x00000004;
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 timestamp = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000004);
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private int impIdx_ ;
      /**
       * <pre>
       * Impression index within the request
       * </pre>
       *
       * <code>optional uint32 imp_idx = 4;</code>
       * @return Whether the impIdx field is set.
       */
      @java.lang.Override
      public boolean hasImpIdx() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <pre>
       * Impression index within the request
       * </pre>
       *
       * <code>optional uint32 imp_idx = 4;</code>
       * @return The impIdx.
       */
      @java.lang.Override
      public int getImpIdx() {
        return impIdx_;
      }
      /**
       * <pre>
       * Impression index within the request
       * </pre>
       *
       * <code>optional uint32 imp_idx = 4;</code>
       * @param value The impIdx to set.
       * @return This builder for chaining.
       */
      public Builder setImpIdx(int value) {
        bitField0_ |= 0x00000008;
        impIdx_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Impression index within the request
       * </pre>
       *
       * <code>optional uint32 imp_idx = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearImpIdx() {
        bitField0_ = (bitField0_ & ~0x00000008);
        impIdx_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:base.EventId)
    }

    // @@protoc_insertion_point(class_scope:base.EventId)
    private static final com.beeswax.base.Eventid.EventId DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.beeswax.base.Eventid.EventId();
    }

    public static com.beeswax.base.Eventid.EventId getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<EventId>
        PARSER = new com.google.protobuf.AbstractParser<EventId>() {
      @java.lang.Override
      public EventId parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new EventId(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<EventId> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EventId> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.beeswax.base.Eventid.EventId getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AdGroupIdOrBuilder extends
      // @@protoc_insertion_point(interface_extends:base.AdGroupId)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string buzz_key = 1;</code>
     * @return Whether the buzzKey field is set.
     */
    boolean hasBuzzKey();
    /**
     * <code>optional string buzz_key = 1;</code>
     * @return The buzzKey.
     */
    java.lang.String getBuzzKey();
    /**
     * <code>optional string buzz_key = 1;</code>
     * @return The bytes for buzzKey.
     */
    com.google.protobuf.ByteString
        getBuzzKeyBytes();

    /**
     * <code>optional uint64 accountid = 2;</code>
     * @return Whether the accountid field is set.
     */
    boolean hasAccountid();
    /**
     * <code>optional uint64 accountid = 2;</code>
     * @return The accountid.
     */
    long getAccountid();

    /**
     * <code>optional uint64 campaignid = 3;</code>
     * @return Whether the campaignid field is set.
     */
    boolean hasCampaignid();
    /**
     * <code>optional uint64 campaignid = 3;</code>
     * @return The campaignid.
     */
    long getCampaignid();

    /**
     * <code>optional uint64 lineitemid = 4;</code>
     * @return Whether the lineitemid field is set.
     */
    boolean hasLineitemid();
    /**
     * <code>optional uint64 lineitemid = 4;</code>
     * @return The lineitemid.
     */
    long getLineitemid();
  }
  /**
   * <pre>
   * Next Tag: 5
   * </pre>
   *
   * Protobuf type {@code base.AdGroupId}
   */
  public static final class AdGroupId extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:base.AdGroupId)
      AdGroupIdOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AdGroupId.newBuilder() to construct.
    private AdGroupId(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AdGroupId() {
      buzzKey_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new AdGroupId();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AdGroupId(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              buzzKey_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              accountid_ = input.readUInt64();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              campaignid_ = input.readUInt64();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              lineitemid_ = input.readUInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.beeswax.base.Eventid.internal_static_base_AdGroupId_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.beeswax.base.Eventid.internal_static_base_AdGroupId_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.beeswax.base.Eventid.AdGroupId.class, com.beeswax.base.Eventid.AdGroupId.Builder.class);
    }

    private int bitField0_;
    public static final int BUZZ_KEY_FIELD_NUMBER = 1;
    private volatile java.lang.Object buzzKey_;
    /**
     * <code>optional string buzz_key = 1;</code>
     * @return Whether the buzzKey field is set.
     */
    @java.lang.Override
    public boolean hasBuzzKey() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string buzz_key = 1;</code>
     * @return The buzzKey.
     */
    @java.lang.Override
    public java.lang.String getBuzzKey() {
      java.lang.Object ref = buzzKey_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          buzzKey_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string buzz_key = 1;</code>
     * @return The bytes for buzzKey.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getBuzzKeyBytes() {
      java.lang.Object ref = buzzKey_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        buzzKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ACCOUNTID_FIELD_NUMBER = 2;
    private long accountid_;
    /**
     * <code>optional uint64 accountid = 2;</code>
     * @return Whether the accountid field is set.
     */
    @java.lang.Override
    public boolean hasAccountid() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional uint64 accountid = 2;</code>
     * @return The accountid.
     */
    @java.lang.Override
    public long getAccountid() {
      return accountid_;
    }

    public static final int CAMPAIGNID_FIELD_NUMBER = 3;
    private long campaignid_;
    /**
     * <code>optional uint64 campaignid = 3;</code>
     * @return Whether the campaignid field is set.
     */
    @java.lang.Override
    public boolean hasCampaignid() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional uint64 campaignid = 3;</code>
     * @return The campaignid.
     */
    @java.lang.Override
    public long getCampaignid() {
      return campaignid_;
    }

    public static final int LINEITEMID_FIELD_NUMBER = 4;
    private long lineitemid_;
    /**
     * <code>optional uint64 lineitemid = 4;</code>
     * @return Whether the lineitemid field is set.
     */
    @java.lang.Override
    public boolean hasLineitemid() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional uint64 lineitemid = 4;</code>
     * @return The lineitemid.
     */
    @java.lang.Override
    public long getLineitemid() {
      return lineitemid_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, buzzKey_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeUInt64(2, accountid_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeUInt64(3, campaignid_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeUInt64(4, lineitemid_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, buzzKey_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, accountid_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, campaignid_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(4, lineitemid_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.beeswax.base.Eventid.AdGroupId)) {
        return super.equals(obj);
      }
      com.beeswax.base.Eventid.AdGroupId other = (com.beeswax.base.Eventid.AdGroupId) obj;

      if (hasBuzzKey() != other.hasBuzzKey()) return false;
      if (hasBuzzKey()) {
        if (!getBuzzKey()
            .equals(other.getBuzzKey())) return false;
      }
      if (hasAccountid() != other.hasAccountid()) return false;
      if (hasAccountid()) {
        if (getAccountid()
            != other.getAccountid()) return false;
      }
      if (hasCampaignid() != other.hasCampaignid()) return false;
      if (hasCampaignid()) {
        if (getCampaignid()
            != other.getCampaignid()) return false;
      }
      if (hasLineitemid() != other.hasLineitemid()) return false;
      if (hasLineitemid()) {
        if (getLineitemid()
            != other.getLineitemid()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasBuzzKey()) {
        hash = (37 * hash) + BUZZ_KEY_FIELD_NUMBER;
        hash = (53 * hash) + getBuzzKey().hashCode();
      }
      if (hasAccountid()) {
        hash = (37 * hash) + ACCOUNTID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getAccountid());
      }
      if (hasCampaignid()) {
        hash = (37 * hash) + CAMPAIGNID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getCampaignid());
      }
      if (hasLineitemid()) {
        hash = (37 * hash) + LINEITEMID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getLineitemid());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.beeswax.base.Eventid.AdGroupId parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.beeswax.base.Eventid.AdGroupId parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.beeswax.base.Eventid.AdGroupId parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.beeswax.base.Eventid.AdGroupId parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.beeswax.base.Eventid.AdGroupId parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.beeswax.base.Eventid.AdGroupId parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.beeswax.base.Eventid.AdGroupId parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.beeswax.base.Eventid.AdGroupId parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.beeswax.base.Eventid.AdGroupId parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.beeswax.base.Eventid.AdGroupId parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.beeswax.base.Eventid.AdGroupId parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.beeswax.base.Eventid.AdGroupId parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.beeswax.base.Eventid.AdGroupId prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Next Tag: 5
     * </pre>
     *
     * Protobuf type {@code base.AdGroupId}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:base.AdGroupId)
        com.beeswax.base.Eventid.AdGroupIdOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.beeswax.base.Eventid.internal_static_base_AdGroupId_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.beeswax.base.Eventid.internal_static_base_AdGroupId_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.beeswax.base.Eventid.AdGroupId.class, com.beeswax.base.Eventid.AdGroupId.Builder.class);
      }

      // Construct using com.beeswax.base.Eventid.AdGroupId.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        buzzKey_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        accountid_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        campaignid_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        lineitemid_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.beeswax.base.Eventid.internal_static_base_AdGroupId_descriptor;
      }

      @java.lang.Override
      public com.beeswax.base.Eventid.AdGroupId getDefaultInstanceForType() {
        return com.beeswax.base.Eventid.AdGroupId.getDefaultInstance();
      }

      @java.lang.Override
      public com.beeswax.base.Eventid.AdGroupId build() {
        com.beeswax.base.Eventid.AdGroupId result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.beeswax.base.Eventid.AdGroupId buildPartial() {
        com.beeswax.base.Eventid.AdGroupId result = new com.beeswax.base.Eventid.AdGroupId(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.buzzKey_ = buzzKey_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.accountid_ = accountid_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.campaignid_ = campaignid_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.lineitemid_ = lineitemid_;
          to_bitField0_ |= 0x00000008;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.beeswax.base.Eventid.AdGroupId) {
          return mergeFrom((com.beeswax.base.Eventid.AdGroupId)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.beeswax.base.Eventid.AdGroupId other) {
        if (other == com.beeswax.base.Eventid.AdGroupId.getDefaultInstance()) return this;
        if (other.hasBuzzKey()) {
          bitField0_ |= 0x00000001;
          buzzKey_ = other.buzzKey_;
          onChanged();
        }
        if (other.hasAccountid()) {
          setAccountid(other.getAccountid());
        }
        if (other.hasCampaignid()) {
          setCampaignid(other.getCampaignid());
        }
        if (other.hasLineitemid()) {
          setLineitemid(other.getLineitemid());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.beeswax.base.Eventid.AdGroupId parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.beeswax.base.Eventid.AdGroupId) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object buzzKey_ = "";
      /**
       * <code>optional string buzz_key = 1;</code>
       * @return Whether the buzzKey field is set.
       */
      public boolean hasBuzzKey() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional string buzz_key = 1;</code>
       * @return The buzzKey.
       */
      public java.lang.String getBuzzKey() {
        java.lang.Object ref = buzzKey_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            buzzKey_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string buzz_key = 1;</code>
       * @return The bytes for buzzKey.
       */
      public com.google.protobuf.ByteString
          getBuzzKeyBytes() {
        java.lang.Object ref = buzzKey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          buzzKey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string buzz_key = 1;</code>
       * @param value The buzzKey to set.
       * @return This builder for chaining.
       */
      public Builder setBuzzKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        buzzKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string buzz_key = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearBuzzKey() {
        bitField0_ = (bitField0_ & ~0x00000001);
        buzzKey_ = getDefaultInstance().getBuzzKey();
        onChanged();
        return this;
      }
      /**
       * <code>optional string buzz_key = 1;</code>
       * @param value The bytes for buzzKey to set.
       * @return This builder for chaining.
       */
      public Builder setBuzzKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        buzzKey_ = value;
        onChanged();
        return this;
      }

      private long accountid_ ;
      /**
       * <code>optional uint64 accountid = 2;</code>
       * @return Whether the accountid field is set.
       */
      @java.lang.Override
      public boolean hasAccountid() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional uint64 accountid = 2;</code>
       * @return The accountid.
       */
      @java.lang.Override
      public long getAccountid() {
        return accountid_;
      }
      /**
       * <code>optional uint64 accountid = 2;</code>
       * @param value The accountid to set.
       * @return This builder for chaining.
       */
      public Builder setAccountid(long value) {
        bitField0_ |= 0x00000002;
        accountid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 accountid = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearAccountid() {
        bitField0_ = (bitField0_ & ~0x00000002);
        accountid_ = 0L;
        onChanged();
        return this;
      }

      private long campaignid_ ;
      /**
       * <code>optional uint64 campaignid = 3;</code>
       * @return Whether the campaignid field is set.
       */
      @java.lang.Override
      public boolean hasCampaignid() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional uint64 campaignid = 3;</code>
       * @return The campaignid.
       */
      @java.lang.Override
      public long getCampaignid() {
        return campaignid_;
      }
      /**
       * <code>optional uint64 campaignid = 3;</code>
       * @param value The campaignid to set.
       * @return This builder for chaining.
       */
      public Builder setCampaignid(long value) {
        bitField0_ |= 0x00000004;
        campaignid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 campaignid = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearCampaignid() {
        bitField0_ = (bitField0_ & ~0x00000004);
        campaignid_ = 0L;
        onChanged();
        return this;
      }

      private long lineitemid_ ;
      /**
       * <code>optional uint64 lineitemid = 4;</code>
       * @return Whether the lineitemid field is set.
       */
      @java.lang.Override
      public boolean hasLineitemid() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional uint64 lineitemid = 4;</code>
       * @return The lineitemid.
       */
      @java.lang.Override
      public long getLineitemid() {
        return lineitemid_;
      }
      /**
       * <code>optional uint64 lineitemid = 4;</code>
       * @param value The lineitemid to set.
       * @return This builder for chaining.
       */
      public Builder setLineitemid(long value) {
        bitField0_ |= 0x00000008;
        lineitemid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 lineitemid = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearLineitemid() {
        bitField0_ = (bitField0_ & ~0x00000008);
        lineitemid_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:base.AdGroupId)
    }

    // @@protoc_insertion_point(class_scope:base.AdGroupId)
    private static final com.beeswax.base.Eventid.AdGroupId DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.beeswax.base.Eventid.AdGroupId();
    }

    public static com.beeswax.base.Eventid.AdGroupId getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<AdGroupId>
        PARSER = new com.google.protobuf.AbstractParser<AdGroupId>() {
      @java.lang.Override
      public AdGroupId parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AdGroupId(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AdGroupId> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AdGroupId> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.beeswax.base.Eventid.AdGroupId getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_base_EventId_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_base_EventId_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_base_AdGroupId_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_base_AdGroupId_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022base/eventid.proto\022\004base\"J\n\007EventId\022\016\n" +
      "\006hostid\030\001 \001(\r\022\013\n\003tid\030\002 \001(\r\022\021\n\ttimestamp\030" +
      "\003 \001(\004\022\017\n\007imp_idx\030\004 \001(\r\"X\n\tAdGroupId\022\020\n\010b" +
      "uzz_key\030\001 \001(\t\022\021\n\taccountid\030\002 \001(\004\022\022\n\ncamp" +
      "aignid\030\003 \001(\004\022\022\n\nlineitemid\030\004 \001(\004B\022\n\020com." +
      "beeswax.base"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_base_EventId_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_base_EventId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_base_EventId_descriptor,
        new java.lang.String[] { "Hostid", "Tid", "Timestamp", "ImpIdx", });
    internal_static_base_AdGroupId_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_base_AdGroupId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_base_AdGroupId_descriptor,
        new java.lang.String[] { "BuzzKey", "Accountid", "Campaignid", "Lineitemid", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
