from behave import *


# @given('(.*) system is up and running')
# def step_impl(context, Sysname):
#     print(Sysname)
# @given(u'(.*) system is up and running')
# def step_impl(context,Sysname):
#     raise NotImplementedError(u'STEP: Given Bidder system is up and running')

#
# @step(u'Bidder system is up and running')
# def step_impl(context):
#     raise NotImplementedError(u'STEP: Given Bidder system is up and running')
#
#
# @when('we update the {testCase} data in the bidder file')
# def step_impl(context, testCase):
#     print(testCase)
#
#
# @then('the amount generated by the bidder file is {Amount} and Response received from beeswax is {Response}')
# def step_impl(context, Amount, Response):
#     print(Response)
