Feature Outline : Bidder system is available and we are able to connect to the bidder system.
Feature
Given Bidder system is up and running
When we update the <testCase> data in the bidder file
Then the amount generated by the bidder file is <Amount>
Examples:
|SysName       |    testCase                                         | Response               |  Amount |
| Bidder       |BidderTestPositiveWithBidAmount                      | 200                    |100      |
| Bidder       |BidderTestPositiveWithBidAmountDefault               | 200                    |100      |
| Bidder       |BidderTestPositiveWithBidAmountRecency               | 200                    |100      |
| Bidder       |BidderTestPositiveWithBidAmountRecencyThreshold      | 202                    |100      |
| Bidder       |BidderTestPositiveWithBidAmountHouseHoldThreshold    | 202                    |100      |
| Bidder       |BidderTestPositiveWithBidAmountViewabilityThresh     | 202                    |100      |
| Bidder       |BidderTestPositiveWithBidAmountHouseHoldthrash       | 202                    |100     |
| Bidder       |BidderTestPositiveWithBidAmountPublisherThrash       | 202                    |100      |